// ---------------------------------------------------------------------------
// WorkOS Project Field Sheet v1 — Validation issue factory
// WORKOS-SHEET-GATE-2
// ---------------------------------------------------------------------------

import type { ImportIssueScope, ImportIssueSeverity, ImportValidationIssue } from "./types";

export function makeIssue(
    code: string,
    severity: ImportIssueSeverity,
    scope: ImportIssueScope,
    message: string,
    extra: Partial<Pick<ImportValidationIssue, "sheetName" | "rowNumber" | "columnName" | "rawValue">> = {},
): ImportValidationIssue {
    return {
        code,
        severity,
        scope,
        message,
        ...extra,
    };
}

export const ISSUE_CODES = {
    UNSUPPORTED_FILE_TYPE: "UNSUPPORTED_FILE_TYPE",
    FILE_TOO_LARGE: "FILE_TOO_LARGE",
    WORKBOOK_OPEN_FAILED: "WORKBOOK_OPEN_FAILED",
    UNSUPPORTED_SCHEMA_VERSION: "UNSUPPORTED_SCHEMA_VERSION",
    MISSING_REQUIRED_SHEET: "MISSING_REQUIRED_SHEET",
    UNKNOWN_WORKSHEET: "UNKNOWN_WORKSHEET",
    HIDDEN_WORKSHEET: "HIDDEN_WORKSHEET",
    HIDDEN_DATA_ROW: "HIDDEN_DATA_ROW",
    MERGED_CELL_IN_DATA_RANGE: "MERGED_CELL_IN_DATA_RANGE",
    FORMULA_IN_DATA_ROW: "FORMULA_IN_DATA_ROW",
    DUPLICATE_HEADER: "DUPLICATE_HEADER",
    UNKNOWN_HEADER: "UNKNOWN_HEADER",
    MISSING_REQUIRED_HEADER: "MISSING_REQUIRED_HEADER",
    SAMPLE_ROW_PRESENT: "SAMPLE_ROW_PRESENT",
    EMPTY_REQUIRED_FIELD: "EMPTY_REQUIRED_FIELD",
    INVALID_ENUM: "INVALID_ENUM",
    INVALID_DATE: "INVALID_DATE",
    INVALID_DATE_RANGE: "INVALID_DATE_RANGE",
    INVALID_BOOLEAN: "INVALID_BOOLEAN",
    INVALID_INTEGER: "INVALID_INTEGER",
    DUPLICATE_EXTERNAL_ROW_ID: "DUPLICATE_EXTERNAL_ROW_ID",
    DUPLICATE_LIST_ITEM: "DUPLICATE_LIST_ITEM",
    ROW_LIMIT_EXCEEDED: "ROW_LIMIT_EXCEEDED",
    CELL_SIZE_EXCEEDED: "CELL_SIZE_EXCEEDED",
    METADATA_PLACEHOLDER_VALUE: "METADATA_PLACEHOLDER_VALUE",
    MACRO_WORKBOOK: "MACRO_WORKBOOK",
    EXTERNAL_LINK: "EXTERNAL_LINK",
    PROJECT_NOT_FOUND: "PROJECT_NOT_FOUND",
    PROJECT_RESOLUTION_AMBIGUOUS: "PROJECT_RESOLUTION_AMBIGUOUS",
    PROJECT_SLUG_REQUIRED: "PROJECT_SLUG_REQUIRED",
    EXISTING_IDENTITY_DUPLICATE: "EXISTING_IDENTITY_DUPLICATE",
    EXISTING_IDENTITY_CONFLICT: "EXISTING_IDENTITY_CONFLICT",
    ARCHIVED_IDENTITY_MATCH: "ARCHIVED_IDENTITY_MATCH",
    CONTENT_DUPLICATE_DIFFERENT_EXTERNAL_ID: "CONTENT_DUPLICATE_DIFFERENT_EXTERNAL_ID",
    BACKLOG_EXACT_DUPLICATE: "BACKLOG_EXACT_DUPLICATE",
    DATABASE_READ_FAILED: "DATABASE_READ_FAILED",
    DATABASE_INTEGRITY_ANOMALY: "DATABASE_INTEGRITY_ANOMALY",
    DRY_RUN_ENTITY_BLOCKED: "DRY_RUN_ENTITY_BLOCKED",
    SIMILAR_IDENTITY_CANDIDATE: "SIMILAR_IDENTITY_CANDIDATE",
} as const;

export type IssueCode = (typeof ISSUE_CODES)[keyof typeof ISSUE_CODES];
