"use client";

import { useCallback, useEffect, useState } from "react";
import { Modal } from "@/components/ui/Modal";
import ConfirmDialog from "@/components/ConfirmDialog";
import type { AIResourceAvailability, AIResourceCostTier, AIResourceProfile } from "@/lib/assignment/types";
import { bangkokDateTimeLocalToIso, isoToBangkokDateTimeLocal } from "./resourceTime";

type Form = { provider_key: string; display_name: string; availability: AIResourceAvailability; remaining_percent: string; reset_at: string; cost_tier: AIResourceCostTier | ""; notes: string };
const initialForm: Form = { provider_key: "", display_name: "", availability: "unknown", remaining_percent: "", reset_at: "", cost_tier: "", notes: "" };
const inputClass = "w-full rounded-lg border border-theme-input-border bg-theme-input-bg px-3 py-2 text-sm text-theme-primary outline-none focus:border-blue-500";

async function json<T>(url: string, init?: RequestInit): Promise<T> {
    const response = await fetch(url, { cache: "no-store", ...init }); const data = await response.json().catch(() => ({}));
    if (!response.ok) throw new Error(data.error || `Request failed (${response.status})`); return data as T;
}

export function AIResourceStatusPanel() {
    const [profiles, setProfiles] = useState<AIResourceProfile[]>([]);
    const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [panelError, setPanelError] = useState<string | null>(null);
    const [modalError, setModalError] = useState<string | null>(null); const [deleteError, setDeleteError] = useState<string | null>(null);
    const [open, setOpen] = useState(false); const [editing, setEditing] = useState<AIResourceProfile | null>(null); const [deleting, setDeleting] = useState<AIResourceProfile | null>(null); const [form, setForm] = useState<Form>(initialForm);
    const load = useCallback(async () => { setLoading(true); setPanelError(null); try { setProfiles((await json<{ profiles: AIResourceProfile[] }>("/api/ai-resources")).profiles); } catch (reason) { setPanelError(reason instanceof Error ? reason.message : "โหลดสถานะ AI ไม่สำเร็จ"); } finally { setLoading(false); } }, []);
    useEffect(() => { void load(); }, [load]);

    function showCreate() { setEditing(null); setForm(initialForm); setModalError(null); setOpen(true); }
    function showEdit(profile: AIResourceProfile) { setEditing(profile); setModalError(null); setForm({ provider_key: profile.provider_key, display_name: profile.display_name, availability: profile.availability, remaining_percent: profile.remaining_percent?.toString() ?? "", reset_at: isoToBangkokDateTimeLocal(profile.reset_at), cost_tier: profile.cost_tier ?? "", notes: profile.notes ?? "" }); setOpen(true); }
    function updateForm(patch: Partial<Form>) { setModalError(null); setForm(current => ({ ...current, ...patch })); }
    async function save() { setSaving(true); setModalError(null); try { const payload = { display_name: form.display_name, availability: form.availability, remaining_percent: form.remaining_percent === "" ? null : Number(form.remaining_percent), reset_at: bangkokDateTimeLocalToIso(form.reset_at), cost_tier: form.cost_tier || null, notes: form.notes || null, ...(editing ? {} : { provider_key: form.provider_key }) }; await json(editing ? `/api/ai-resources/${editing.id}` : "/api/ai-resources", { method: editing ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); setOpen(false); setModalError(null); await load(); } catch (reason) { setModalError(reason instanceof Error ? reason.message : "บันทึก AI resource ไม่สำเร็จ"); } finally { setSaving(false); } }
    async function remove() { if (!deleting) return; setSaving(true); setDeleteError(null); try { await json(`/api/ai-resources/${deleting.id}`, { method: "DELETE" }); setDeleting(null); await load(); } catch (reason) { setDeleteError(reason instanceof Error ? reason.message : "ลบ AI resource ไม่สำเร็จ"); } finally { setSaving(false); } }

    return <section className="rounded-2xl border border-theme-border bg-theme-card-bg p-5">
        <div className="flex items-start justify-between gap-3"><div><h2 className="font-bold text-theme-primary">AI Resource Status</h2><p className="mt-1 text-sm text-theme-secondary">สถานะทรัพยากร AI ที่กรอกและดูแลด้วยตนเอง</p></div><button onClick={showCreate} className="rounded-lg bg-blue-600 px-3 py-2 text-sm font-semibold text-white hover:bg-blue-500">+ เพิ่ม Provider</button></div>
        {panelError && <div role="alert" className="mt-4 rounded-lg border border-red-500/30 bg-red-500/10 p-3 text-sm text-red-500">{panelError}</div>}
        {loading ? <div className="py-6 text-center text-sm text-theme-muted">กำลังโหลด...</div> : profiles.length === 0 ? <div className="mt-4 rounded-xl border border-dashed border-theme-border p-5 text-center text-sm text-theme-muted">ยังไม่มี AI resource profile — ตัวอย่างชื่อ: Codex, Claude / GPT, Gemini</div> : <div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{profiles.map(profile => <article key={profile.id} className="rounded-xl border border-theme-border bg-theme-card-elevated p-4"><div className="flex justify-between gap-2"><div><h3 className="font-semibold text-theme-primary">{profile.display_name}</h3><p className="text-xs text-theme-muted">{profile.provider_key}</p></div><span className="h-fit rounded-full bg-theme-hover px-2 py-1 text-xs font-semibold text-theme-secondary">{profile.availability}</span></div><div className="mt-3 text-xs text-theme-secondary">คงเหลือ: {profile.remaining_percent == null ? "ไม่ระบุ" : `${profile.remaining_percent}%`} · Cost: {profile.cost_tier ?? "ไม่ระบุ"}</div>{profile.reset_at && <div className="mt-1 text-xs text-theme-muted">Reset: {new Date(profile.reset_at).toLocaleString("th-TH")}</div>}{profile.notes && <p className="mt-2 text-xs text-theme-muted">{profile.notes}</p>}<div className="mt-3 flex justify-end gap-2"><button onClick={() => showEdit(profile)} className="rounded-md border border-theme-border px-2 py-1 text-xs text-theme-secondary">แก้ไข</button><button onClick={() => setDeleting(profile)} className="rounded-md border border-red-500/30 px-2 py-1 text-xs text-red-500">ลบ</button></div></article>)}</div>}
        <Modal isOpen={open} title={editing ? "แก้ไข AI Resource" : "เพิ่ม AI Resource"} onClose={() => { setOpen(false); setModalError(null); }} maxWidth="max-w-2xl">{modalError && <div role="alert" className="mb-4 rounded-lg border border-red-500/30 bg-red-500/10 p-3 text-sm text-red-500">{modalError}</div>}<div className="grid gap-4 sm:grid-cols-2"><Field label="Provider Key"><input disabled={Boolean(editing)} value={form.provider_key} onChange={e => updateForm({ provider_key: e.target.value })} placeholder="codex" className={inputClass + " disabled:opacity-60"} /></Field><Field label="Provider Name"><input value={form.display_name} onChange={e => updateForm({ display_name: e.target.value })} placeholder="Codex" className={inputClass} /></Field><Field label="Availability"><select value={form.availability} onChange={e => updateForm({ availability: e.target.value as AIResourceAvailability })} className={inputClass}>{["unknown", "unavailable", "low", "medium", "high"].map(value => <option key={value}>{value}</option>)}</select></Field><Field label="Remaining Percent"><input type="number" min="0" max="100" value={form.remaining_percent} onChange={e => updateForm({ remaining_percent: e.target.value })} className={inputClass} /></Field><Field label="Reset Time"><input type="datetime-local" value={form.reset_at} onChange={e => updateForm({ reset_at: e.target.value })} className={inputClass} /><span className="mt-1 block text-xs text-theme-muted">เวลาไทย (Asia/Bangkok)</span></Field><Field label="Cost Tier"><select value={form.cost_tier} onChange={e => updateForm({ cost_tier: e.target.value as AIResourceCostTier | "" })} className={inputClass}><option value="">ไม่ระบุ</option><option value="low">low</option><option value="medium">medium</option><option value="high">high</option></select></Field><label className="sm:col-span-2 text-sm font-medium text-theme-secondary">Notes<textarea value={form.notes} onChange={e => updateForm({ notes: e.target.value })} className={inputClass + " mt-1 min-h-24"} /></label></div><div className="mt-6 flex justify-end gap-2"><button onClick={() => { setOpen(false); setModalError(null); }} className="rounded-lg border border-theme-border px-4 py-2 text-sm text-theme-secondary">ยกเลิก</button><button disabled={saving || !form.provider_key || !form.display_name} onClick={() => void save()} className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{saving ? "กำลังบันทึก..." : "บันทึก"}</button></div></Modal>
        <ConfirmDialog isOpen={deleting != null} title="ลบ AI Resource Profile" message="ลบเฉพาะข้อมูลสถานะทรัพยากร AI นี้ใช่หรือไม่? Planner items และงานต้นทางจะไม่ถูกลบ" confirmText="ลบ Profile" cancelText="ยกเลิก" danger onCancel={() => { setDeleting(null); setDeleteError(null); }} onConfirm={remove}>{deleteError && <div role="alert" className="rounded-lg border border-red-500/30 bg-red-500/10 p-3 text-sm text-red-500">{deleteError}</div>}</ConfirmDialog>
    </section>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="text-sm font-medium text-theme-secondary">{label}<div className="mt-1">{children}</div></label>; }
