"use client";

import { useState } from "react";
import type { AssignmentRecommendation, AssignmentResult } from "@/lib/assignment/types";
import { ASSIGNMENT_EMPTY_STATES, OWNER_LABELS, formatAssignmentFactor, validateAvailableMinutes } from "./assignmentUi";

export function AssignmentRecommendationPanel({ date, hasDay, itemCount, onViewItem }: { date: string; hasDay: boolean; itemCount: number; onViewItem: (id: string) => void }) {
    const [minutes, setMinutes] = useState(""); const [result, setResult] = useState<AssignmentResult | null>(null); const [dismissed, setDismissed] = useState<string[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null); const [expanded, setExpanded] = useState(false);
    const visible = result?.recommendations.filter(entry => !dismissed.includes(entry.item.id)) ?? [];
    const top = visible[0] ?? null;
    async function refresh() { const validation = validateAvailableMinutes(minutes); if (validation) { setError(validation); return; } setLoading(true); setError(null); setDismissed([]); try { const response = await fetch(`/api/assignment/recommend?date=${date}&available_minutes=${minutes}`, { cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "โหลดคำแนะนำไม่สำเร็จ"); setResult(data); } catch (reason) { setError(reason instanceof Error ? reason.message : "โหลดคำแนะนำไม่สำเร็จ"); } finally { setLoading(false); } }
    const initialMessage = !hasDay ? ASSIGNMENT_EMPTY_STATES.noDay : itemCount === 0 ? ASSIGNMENT_EMPTY_STATES.noItems : !minutes ? ASSIGNMENT_EMPTY_STATES.noMinutes : null;
    return <section className="rounded-2xl border border-theme-border bg-theme-card-bg p-5">
        <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="font-bold text-theme-primary">Recommended Next Assignment</h2><p className="mt-1 text-sm text-theme-secondary">งานที่ Arbor แนะนำให้ทำต่อ จากกฎที่อธิบายได้</p></div><div className="flex flex-wrap gap-2"><label className="text-xs font-medium text-theme-secondary">Available Minutes Remaining<input type="number" min="0" value={minutes} onChange={e => setMinutes(e.target.value)} className="mt-1 w-44 rounded-lg border border-theme-input-border bg-theme-input-bg px-3 py-2 text-sm text-theme-primary" placeholder="เช่น 90" /></label><button disabled={loading || !hasDay || itemCount === 0} onClick={() => void refresh()} className="self-end rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{loading ? "กำลังวิเคราะห์..." : "Refresh recommendation"}</button></div></div>
        {error && <div role="alert" className="mt-4 rounded-lg border border-red-500/30 bg-red-500/10 p-3 text-sm text-red-500">{error}</div>}
        {initialMessage && !top ? <div className="mt-4 rounded-xl border border-dashed border-theme-border p-5 text-center text-sm text-theme-muted">{initialMessage}</div> : !top && result ? <div className="mt-4 rounded-xl border border-dashed border-theme-border p-5 text-center text-sm text-theme-muted">{ASSIGNMENT_EMPTY_STATES.noRecommendation}</div> : top ? <><RecommendationCard recommendation={top} prominent onView={() => onViewItem(top.item.id)} onDefer={() => setDismissed(current => [...current, top.item.id])} /><button onClick={() => setExpanded(value => !value)} className="mt-3 text-sm font-medium text-blue-500">{expanded ? "ซ่อนรายการอื่น" : `ดูคำแนะนำลำดับถัดไป (${Math.max(visible.length - 1, 0)})`}</button>{expanded && <div className="mt-3 space-y-3">{visible.slice(1).map(entry => <RecommendationCard key={entry.item.id} recommendation={entry} onView={() => onViewItem(entry.item.id)} onDefer={() => setDismissed(current => [...current, entry.item.id])} />)}</div>}</> : null}
    </section>;
}

function RecommendationCard({ recommendation, prominent = false, onView, onDefer }: { recommendation: AssignmentRecommendation; prominent?: boolean; onView: () => void; onDefer: () => void }) {
    return <article className={`mt-4 rounded-xl border p-4 ${prominent ? "border-blue-500/40 bg-blue-500/5" : "border-theme-border bg-theme-card-elevated"}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="text-xs font-bold uppercase tracking-wider text-blue-500">Score {recommendation.total_score}</div><h3 className="mt-1 text-lg font-bold text-theme-primary">{recommendation.item.source_title}</h3><p className="text-xs text-theme-muted">{recommendation.item.source_project_name || recommendation.item.source_workspace || "ไม่ระบุบริบท"}</p></div><div className="text-right text-sm text-theme-secondary"><div>ผู้รับผิดชอบที่แนะนำ: <strong>{OWNER_LABELS[recommendation.recommended_owner]}</strong></div><div>{recommendation.estimated_duration == null ? "ไม่ระบุเวลา" : `${recommendation.estimated_duration} นาที`} · {recommendation.recommended_block ?? "ไม่ระบุ block"}</div></div></div><div className="mt-3"><h4 className="text-xs font-bold text-theme-secondary">เหตุผลที่แนะนำ</h4><ul className="mt-1 space-y-1 text-xs text-theme-muted">{recommendation.factors.map(entry => <li key={entry.key}>• {formatAssignmentFactor(entry)}</li>)}</ul></div>{recommendation.warnings.length > 0 && <div className="mt-3 rounded-lg bg-amber-500/10 p-3"><h4 className="text-xs font-bold text-amber-600">ข้อควรระวัง</h4>{recommendation.warnings.map(warning => <p key={warning} className="mt-1 text-xs text-amber-600">• {warning}</p>)}</div>}<div className="mt-3 flex justify-end gap-2"><button onClick={onView} className="rounded-lg border border-theme-border px-3 py-1.5 text-xs text-theme-secondary">ดูรายการ</button><button onClick={onDefer} className="rounded-lg border border-theme-border px-3 py-1.5 text-xs text-theme-secondary">พักคำแนะนำนี้</button></div></article>;
}
