import { describe, expect, it } from "vitest";
import Database from "better-sqlite3";
import { CreateAIResourceProfileSchema, PatchAIResourceProfileSchema } from "@/lib/assignment/resourceValidation";

function db() { const value = new Database(":memory:"); value.exec(`CREATE TABLE ai_resource_profiles (id TEXT PRIMARY KEY, provider_key TEXT NOT NULL UNIQUE, display_name TEXT NOT NULL, availability TEXT NOT NULL DEFAULT 'unknown', remaining_percent INTEGER NULL CHECK (remaining_percent IS NULL OR remaining_percent BETWEEN 0 AND 100), reset_at TEXT NULL, cost_tier TEXT NULL, notes TEXT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL)`); return value; }

describe("AI resource profiles", () => {
    it("GET-style SELECT has no side effects", () => { const database = db(); expect(database.prepare("SELECT * FROM ai_resource_profiles").all()).toEqual([]); expect((database.prepare("SELECT COUNT(*) count FROM ai_resource_profiles").get() as { count: number }).count).toBe(0); database.close(); });
    it("validates and creates an AI resource profile with Thai notes", () => { const parsed = CreateAIResourceProfileSchema.parse({ provider_key: "codex", display_name: "Codex", availability: "high", remaining_percent: 80, reset_at: null, cost_tier: "medium", notes: "พร้อมใช้สำหรับงานเขียน" }); const database = db(); database.prepare("INSERT INTO ai_resource_profiles VALUES (?, ?, ?, ?, ?, ?, ?, ?, datetime('now'), datetime('now'))").run("AI-1", parsed.provider_key, parsed.display_name, parsed.availability, parsed.remaining_percent, parsed.reset_at, parsed.cost_tier, parsed.notes); expect((database.prepare("SELECT notes FROM ai_resource_profiles").get() as { notes: string }).notes).toBe("พร้อมใช้สำหรับงานเขียน"); database.close(); });
    it("rejects duplicate provider_key", () => { const database = db(); database.prepare("INSERT INTO ai_resource_profiles VALUES ('1','codex','Codex','high',NULL,NULL,NULL,NULL,datetime('now'),datetime('now'))").run(); expect(() => database.prepare("INSERT INTO ai_resource_profiles VALUES ('2','codex','Other','low',NULL,NULL,NULL,NULL,datetime('now'),datetime('now'))").run()).toThrow(/UNIQUE/); database.close(); });
    it("rejects remaining_percent below zero", () => { expect(CreateAIResourceProfileSchema.safeParse({ provider_key: "codex", display_name: "Codex", remaining_percent: -1 }).success).toBe(false); });
    it("rejects remaining_percent above 100", () => { expect(CreateAIResourceProfileSchema.safeParse({ provider_key: "codex", display_name: "Codex", remaining_percent: 101 }).success).toBe(false); });
    it("validates a resource status update without provider_key", () => { expect(PatchAIResourceProfileSchema.parse({ availability: "low", remaining_percent: 25 })).toEqual({ availability: "low", remaining_percent: 25 }); });
    it("PATCH notes only does not inject availability", () => { expect(PatchAIResourceProfileSchema.parse({ notes: "อัปเดตหมายเหตุ" })).toEqual({ notes: "อัปเดตหมายเหตุ" }); });
    it("PATCH reset_at only does not inject availability", () => { expect(PatchAIResourceProfileSchema.parse({ reset_at: "2026-07-15T10:00:00.000Z" })).toEqual({ reset_at: "2026-07-15T10:00:00.000Z" }); });
    it("accepts an empty PATCH as an unchanged profile request", () => { expect(PatchAIResourceProfileSchema.parse({})).toEqual({}); });
    it("PATCH explicit availability updates correctly", () => { expect(PatchAIResourceProfileSchema.parse({ availability: "high" })).toEqual({ availability: "high" }); });
    it("PATCH cannot change provider_key", () => { expect(PatchAIResourceProfileSchema.safeParse({ provider_key: "gemini" }).success).toBe(false); });
    it("deletes only the selected profile", () => { const database = db(); database.prepare("INSERT INTO ai_resource_profiles VALUES ('1','codex','Codex','high',NULL,NULL,NULL,NULL,datetime('now'),datetime('now'))").run(); database.prepare("INSERT INTO ai_resource_profiles VALUES ('2','gemini','Gemini','medium',NULL,NULL,NULL,NULL,datetime('now'),datetime('now'))").run(); database.prepare("DELETE FROM ai_resource_profiles WHERE id = ?").run("1"); expect((database.prepare("SELECT COUNT(*) count FROM ai_resource_profiles").get() as { count: number }).count).toBe(1); database.close(); });
    it("rejects an invalid reset_at value", () => { expect(CreateAIResourceProfileSchema.safeParse({ provider_key: "codex", display_name: "Codex", reset_at: "tomorrow" }).success).toBe(false); });
});
