import { describe, expect, it } from "vitest";
import { recommendAssignments } from "@/lib/assignment/engine";
import type { AIResourceProfile, AssignmentCandidate, AssignmentContext } from "@/lib/assignment/types";

function candidate(id: string, overrides: Partial<AssignmentCandidate> = {}): AssignmentCandidate {
    return { id, source_type: "task", source_id: `TASK-${id}`, source_title: `งาน ${id}`, source_status: "planned", source_workspace: "content", source_project_id: null, source_project_name: null, source_missing: false, work_mode: "focus", priority: "normal", estimated_minutes: 60, start_time: null, end_time: null, ai_provider_key: null, energy_level: "medium", scheduled_block: "morning_focus", planned_order: 0, planner_status: "planned", ...overrides };
}
function resource(availability: AIResourceProfile["availability"]): AIResourceProfile { return { id: "AI-1", provider_key: "codex", display_name: "Codex", availability, remaining_percent: 80, reset_at: null, cost_tier: "medium", notes: null, created_at: "", updated_at: "" }; }
function context(candidates: AssignmentCandidate[], overrides: Partial<AssignmentContext> = {}): AssignmentContext { return { plan_date: "2026-07-15", day_energy_level: "high", daily_capacity_minutes: 480, available_minutes: 90, candidates, ai_resources: [], ...overrides }; }

describe("deterministic assignment engine", () => {
    it("ranks a critical ready item above a normal planned item", () => { const result = recommendAssignments(context([candidate("normal"), candidate("critical", { priority: "critical", planner_status: "ready" })])); expect(result.top_recommendation?.item.id).toBe("critical"); });
    it("strongly penalizes a blocked item", () => { const result = recommendAssignments(context([candidate("ready", { planner_status: "ready" }), candidate("blocked", { priority: "critical", planner_status: "blocked" })])); expect(result.recommendations.find(entry => entry.item.id === "blocked")!.total_score).toBeLessThan(result.top_recommendation!.total_score); });
    it("excludes completed items", () => { expect(recommendAssignments(context([candidate("done", { planner_status: "completed" })])).recommendations).toHaveLength(0); });
    it("excludes missing-source items", () => { expect(recommendAssignments(context([candidate("missing", { source_missing: true })])).recommendations).toHaveLength(0); });
    it("ranks a fitting task above an oversized task", () => { const result = recommendAssignments(context([candidate("large", { estimated_minutes: 180 }), candidate("fit", { estimated_minutes: 60 })])); expect(result.top_recommendation?.item.id).toBe("fit"); });
    it("penalizes high-energy work on a low-energy day", () => { const result = recommendAssignments(context([candidate("high", { energy_level: "high" }), candidate("low", { energy_level: "low" })], { day_energy_level: "low" })); expect(result.top_recommendation?.item.id).toBe("low"); });
    it("penalizes AI execution when its selected provider is unavailable", () => { const entry = recommendAssignments(context([candidate("ai", { work_mode: "ai_execution", ai_provider_key: "codex" })], { ai_resources: [resource("unavailable")] })).top_recommendation!; expect(entry.factors.find(value => value.key === "ai_resource_fit")?.score).toBe(-25); expect(entry.recommended_owner).toBe("defer"); });
    it("rewards AI execution when the matching Codex provider is high", () => { const entry = recommendAssignments(context([candidate("ai", { work_mode: "ai_execution", ai_provider_key: "codex" })], { ai_resources: [resource("high")] })).top_recommendation!; expect(entry.factors.find(value => value.key === "ai_resource_fit")?.score).toBe(10); expect(entry.recommended_owner).toBe("codex"); });
    it("does not fall back from unavailable Codex to unrelated high Gemini", () => { const gemini = { ...resource("high"), id: "AI-2", provider_key: "gemini", display_name: "Gemini" }; const entry = recommendAssignments(context([candidate("ai", { work_mode: "ai_execution", ai_provider_key: "codex" })], { ai_resources: [resource("unavailable"), gemini] })).top_recommendation!; expect(entry.matched_resource?.provider_key).toBe("codex"); expect(entry.factors.find(value => value.key === "ai_resource_fit")?.score).toBe(-25); });
    it("uses an unknown penalty when provider is unspecified", () => { const entry = recommendAssignments(context([candidate("ai", { work_mode: "ai_execution" })], { ai_resources: [resource("high")] })).top_recommendation!; expect(entry.matched_resource).toBeNull(); expect(entry.factors.find(value => value.key === "ai_resource_fit")?.score).toBe(-8); expect(entry.warnings).toContain("ยังไม่ได้ระบุผู้ให้บริการ AI สำหรับงานนี้"); });
    it("handles a deleted referenced provider safely", () => { const entry = recommendAssignments(context([candidate("ai", { work_mode: "ai_execution", ai_provider_key: "deleted-provider" })], { ai_resources: [] })).top_recommendation!; expect(entry.factors.find(value => value.key === "ai_resource_fit")?.score).toBe(-25); expect(entry.recommended_owner).toBe("defer"); });
    it("does not label non-Codex provider work as Codex", () => { const gemini = { ...resource("high"), provider_key: "gemini", display_name: "Gemini" }; const entry = recommendAssignments(context([candidate("ai", { work_mode: "ai_execution", ai_provider_key: "gemini" })], { ai_resources: [gemini] })).top_recommendation!; expect(entry.recommended_owner).toBe("arbor_assistant"); });
    it("is deterministic for identical input", () => { const input = context([candidate("b"), candidate("a")]); expect(recommendAssignments(input)).toEqual(recommendAssignments(input)); expect(recommendAssignments(input).top_recommendation?.item.id).toBe("a"); });
    it("includes Thai-language reasons for every factor", () => { const entry = recommendAssignments(context([candidate("one")])).top_recommendation!; expect(entry.factors.length).toBeGreaterThan(0); expect(entry.factors.every(value => value.reason.length > 0)).toBe(true); });
    it("contains no Astro factors", () => { const keys = recommendAssignments(context([candidate("one")])).top_recommendation!.factors.map(value => value.key); expect(keys.some(key => key.toLowerCase().includes("astro"))).toBe(false); });
    it("rewards staying in the context of work already doing", () => { const result = recommendAssignments(context([candidate("doing", { planner_status: "doing", source_workspace: "content" }), candidate("same", { source_workspace: "content" }), candidate("different", { source_workspace: "personal" })])); const same = result.recommendations.find(entry => entry.item.id === "same")!; const different = result.recommendations.find(entry => entry.item.id === "different")!; expect(same.factors.find(value => value.key === "context_switch")?.score).toBe(5); expect(different.factors.find(value => value.key === "context_switch")?.score).toBe(-10); });
});
