import { afterEach, describe, expect, it, vi } from "vitest";
import { AiRuntimeError } from "@/lib/ai/openaiReadAnalyze";
import { runDeepSeekReadAnalyze } from "@/lib/ai/deepseekReadAnalyze";
const payload={analysisMode:"summary_findings_evidence" as const,sourceLabel:"Source A",sourceText:"Alpha beta"};
const valid={summary:"Summary",findings:["Finding"],evidence:["Evidence"],limitations:[]};
function responseFor(value:unknown,status="completed"):Response{return new Response(JSON.stringify({status,output:[{type:"reasoning",summary:[]},{type:"message",content:[{type:"output_text",text:JSON.stringify(value)}]}]}),{status:200,headers:{"content-type":"application/json"}})}
function code(error:unknown){return error instanceof AiRuntimeError?error.code:undefined}
afterEach(()=>{vi.useRealTimers();vi.restoreAllMocks()});
describe("ACC-P5-PROV-03 DeepSeek runtime adapter",()=>{
 it("fails closed before fetch without credential",async()=>{const fetchImpl=vi.fn();await expect(runDeepSeekReadAnalyze(payload,{apiKey:null,fetchImpl})).rejects.toSatisfy((e:unknown)=>code(e)==="AI_NOT_CONFIGURED");expect(fetchImpl).not.toHaveBeenCalled()});
 it("sends exact bounded request with no store strict or tools",async()=>{const fetchImpl=vi.fn().mockResolvedValue(responseFor(valid));await expect(runDeepSeekReadAnalyze(payload,{apiKey:"test-key",fetchImpl})).resolves.toEqual(valid);const [url,init]=fetchImpl.mock.calls[0] as [string,RequestInit];expect(url).toBe("https://api.deepseek.com/responses");expect(init.method).toBe("POST");expect((init.headers as Record<string,string>).Authorization).toBe("Bearer test-key");const req=JSON.parse(String(init.body));expect(req.model).toBe("deepseek-v4-flash");expect(req.reasoning).toEqual({effort:"low"});expect(req.max_output_tokens).toBe(3072);expect(req.store).toBeUndefined();expect(req.strict).toBeUndefined();expect(req.tools).toBeUndefined();expect(req.text.format.type).toBe("json_schema");expect(req.text.format.name).toBe("workos_read_analyze_result");expect(req.text.format.strict).toBeUndefined();expect(JSON.stringify(req.input)).toContain("untrusted data")});
 it("accepts completed output with reasoning item",async()=>{const fetchImpl=vi.fn().mockResolvedValue(responseFor(valid));await expect(runDeepSeekReadAnalyze(payload,{apiKey:"test-key",fetchImpl})).resolves.toEqual(valid)});
 it.each([["failed","AI_PROVIDER_FAILED"],["incomplete","AI_RESULT_INVALID"],["in_progress","AI_RESULT_INVALID"]])("maps %s fail-closed",async(status,expected)=>{const fetchImpl=vi.fn().mockResolvedValue(responseFor(valid,status));await expect(runDeepSeekReadAnalyze(payload,{apiKey:"test-key",fetchImpl})).rejects.toSatisfy((e:unknown)=>code(e)===expected)});
 it("rejects malformed and schema-invalid output",async()=>{const malformed=vi.fn().mockResolvedValue(new Response(JSON.stringify({status:"completed",output:[{type:"message",content:[{type:"output_text",text:"not-json"}]}]}),{status:200}));await expect(runDeepSeekReadAnalyze(payload,{apiKey:"test-key",fetchImpl:malformed})).rejects.toSatisfy((e:unknown)=>code(e)==="AI_RESULT_INVALID");const invalid=vi.fn().mockResolvedValue(responseFor({...valid,unexpected:true}));await expect(runDeepSeekReadAnalyze(payload,{apiKey:"test-key",fetchImpl:invalid})).rejects.toSatisfy((e:unknown)=>code(e)==="AI_RESULT_INVALID")});
 it("maps non-2xx and timeout",async()=>{const nonOk=vi.fn().mockResolvedValue(new Response("no",{status:500}));await expect(runDeepSeekReadAnalyze(payload,{apiKey:"test-key",fetchImpl:nonOk})).rejects.toSatisfy((e:unknown)=>code(e)==="AI_PROVIDER_FAILED");vi.useFakeTimers();const fetchImpl=vi.fn((_u:string,init?:RequestInit)=>new Promise<Response>((_r,reject)=>init?.signal?.addEventListener("abort",()=>reject(new DOMException("Aborted","AbortError")))));const pending=runDeepSeekReadAnalyze(payload,{apiKey:"test-key",fetchImpl:fetchImpl as typeof fetch,timeoutMs:1000});const assertion=expect(pending).rejects.toSatisfy((e:unknown)=>code(e)==="AI_TIMEOUT");await vi.advanceTimersByTimeAsync(1000);await assertion});
});
